### ISSUE TITLE
[BUG] Costumes and Camera system not working.

### ISSUE THREAD

**Issue by TheGermanWolfYT** [Mihro/MNAF-Senary-Saloon#14]
**Describe the bug**
The costumes and the camera system is bugged out and don't work. The camera system only teleports you to the camera you click on. The costumes don't work and says the dress stuff is unknown even the Bonnie signs behind the bar.

**Versions:**
 - [x] Minecraft: Java Edition 1.18.2
 - [x] Optifine 1.18.2 HD_U_H7

**Comment by Mihro** [comment]
The map is available for Minecraft Java **1.16.5 ONLY**.
Some features - like the ones you described - won't work in higher versions.
