### ISSUE TITLE
[BUG] A Resource Pack Problem

### ISSUE THREAD

**Issue by FireRixy** [Mihro/MNAF-Senary-Saloon#17]
I have a bug when doing the server. I put it into a server of my own and imported the resource pack. But the Problem is the armor for the animatronics are missing. So I was wondering if their is a missing file that is not included. I wanna play the map with some of my friends and do our own rp. So if their is something missing like resources or anything. Please I would like to know so I could add it. Thank you.

**Comment by Mihro** [comment]
You need to make sure every player:
- [ ] Is playing on Minecraft version 1.16.5.
- [ ] Has Optifine: Version 1.16.5 HD_U_G7 installed.
- [ ] Has a copy of the resource pack for themselves and enabled it.

**Comment by FireRixy** [comment]
Is Optifine required for the suits?

**Comment by FireRixy** [comment]
Is Optifine required for the suits?

**Comment by Mihro** [comment]
Yes. Optifine is required for custom armor textures.
