### ISSUE TITLE
[BUG] The Jail cell door doesn't close

### ISSUE THREAD

**Issue by CrazyAdventuresYT** [Mihro/MNAF-Senary-Saloon#3]
The Jail cell door doesn't close. I first, I though I had to reset the jail door from the book, still didn't closed. I reset the door again and waited about 2 minutes if it spawns in the cool down phase, then I tried again and it still didn't work. IDK what is going on. Please fix it, thanks.

**Versions:**
 - [x] Minecraft: Java Edition 1.16.5
 - [x] Optifine 1.16.5 HD_U_G7

**Additional context**

**Comment by Mihro** [comment]
Thank you for the report.

This was fixed in f509e0d565898944e912824309819c0a9d4fe924 for version [v1.0.1](https://github.com/Mihro/MNAF-Senary-Saloon/releases/tag/v1.0.1).
