### ISSUE TITLE
my outfits are not working

### ISSUE THREAD

**Issue by lillian61** [Mihro/MNAF-Senary-Saloon#5]
none of my outfits are working its not even letting me put any of them on and none of the cams are working it just keeps on teleporting me to the place

**Comment by Mihro** [comment]
Please fill in the issue template when reporting bugs.

This user's issue has been discussed and resolved on Discord:
- They did not read and follow the requirements:
  - Minecraft Java Edition 1.16.5
  - Optifine 1.16.5
